require 'mailwrapper/project_patch'
require 'mailwrapper/issue_category_patch'
require 'mailwrapper/issue_status_patch'
require 'mailwrapper/tracker_patch'
require 'mailwrapper/user_patch'
require 'mailwrapper/projects_helper_patch'
require 'mailwrapper/util'
require 'mailwrapper/issue_observer_patch'
require 'mailwrapper/journal_observer_patch'
require 'mailwrapper/news_observer_patch'
require 'mailwrapper/comment_observer_patch'

